***TAREA***

In [150]:
import pandas as pd
import numpy as np
import json as js
import csv
%pip install openpyxl

victoriabc = pd.read_csv("Victoria BC.csv")
victoriabc

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

,Unnamed: 0,id,scrape_id,last_scraped,host_url,host_location,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_name,host_listings_count,has_availability,number_of_reviews,price
0,0,19898,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/69729,NaN,NaN,f,6,"['email', 'phone']",...,1,0,1,0,NaN,Ryan,1,NaN,0,NaN
1,1,41168,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/173169,"Victoria, Canada",99%,t,6,"['email', 'phone']",...,3,3,0,0,0.50,Ocean Island Garden Suites,3,t,70,"$9,999.00"
2,2,83515,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/455118,"British Columbia, Canada",97%,t,4,"['email', 'phone']",...,2,2,0,0,0.89,Celia,2,t,148,$175.00
3,3,168460,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/802981,"Victoria, Canada",NaN,f,3,"['email', 'phone', 'work_email']",...,1,1,0,0,0.42,Deborah,1,t,64,$200.00
4,4,185732,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/880366,"Victoria, Canada",0%,f,3,"['email', 'phone', 'work_email']",...,3,0,3,0,0.32,Peter,3,t,52,$199.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3946,3946,1315368084757533488,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/548256873,NaN,100%,NaN,6,"['email', 'phone']",...,3,3,0,0,NaN,Swell West,6,t,0,$263.00
3947,3947,1316608634341666791,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/668062525,NaN,NaN,f,1,"['email', 'phone']",...,1,1,0,0,NaN,Charlotte Jane,1,t,0,$128.00
3948,3948,1317141084646533661,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/290549710,"Victoria, Canada",NaN,f,1,"['email', 'phone']",...,1,1,0,0,NaN,Majachani,1,NaN,0,$98.00
3949,3949,1318221712246054906,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/112019210,"Victoria, Canada",91%,t,4,['phone'],...,1,1,0,0,1.00,Troy,1,t,1,$61.00
3950,3950,1318259877390189592,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/32614142,"Victoria, Canada",98%,t,118,"['email', 'phone', 'work_email']",...,53,53,0,0,NaN,Elite Vacation Homes,55,t,0,$148.00

In [151]:
#(a) 5 host names

host_names = victoriabc['host_name']
datos_filtrados_a = victoriabc[victoriabc['host_name'].isin(host_names)]
datos_filtrados_a.to_csv("Victoria BC.csv", index=False)
host_names

0                             Ryan
1       Ocean Island Garden Suites
2                            Celia
3                          Deborah
4                            Peter
                   ...
3946                    Swell West
3947                Charlotte Jane
3948                     Majachani
3949                          Troy
3950          Elite Vacation Homes
Name: host_name, Length: 3951, dtype: object

In [152]:
host_names.to_csv("Datos de Host_Names.csv")

In [153]:
# (b) Anuncios con más de 100 reseñas

if 'number_of_reviews' in victoriabc.columns:
    datosb = victoriabc[victoriabc['number_of_reviews'] > 100]
datosb

,Unnamed: 0,id,scrape_id,last_scraped,host_url,host_location,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_name,host_listings_count,has_availability,number_of_reviews,price
2,2,83515,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/455118,"British Columbia, Canada",97%,t,4,"['email', 'phone']",...,2,2,0,0,0.89,Celia,2,t,148,$175.00
5,5,193366,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/937766,"Victoria, Canada",100%,f,1,"['email', 'phone']",...,1,1,0,0,1.00,Sandra,1,t,157,$135.00
8,8,203416,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/997424,"British Columbia, Canada",98%,f,3,"['email', 'phone']",...,2,2,0,0,3.10,Line Marie,2,t,457,$147.00
9,9,226028,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/1178351,"Victoria, Canada",100%,t,2,"['email', 'phone', 'work_email']",...,2,2,0,0,1.61,Allison,2,t,259,$110.00
11,11,237053,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/1216332,"Victoria, Canada",85%,f,3,"['email', 'phone']",...,2,0,2,0,1.65,Ann,2,t,266,$89.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2699,2699,887793960658346125,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/244435327,"Victoria, Canada",100%,t,2,"['email', 'phone']",...,2,2,0,0,6.45,Garrett,2,t,127,$166.00
2792,2792,908960583232600673,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/46060366,"Sooke, Canada",96%,t,1,"['email', 'phone']",...,1,1,0,0,6.65,Justine And Robert,1,t,126,$99.00
3015,3015,978366514419795869,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/536661076,"Vancouver, Canada",84%,t,5,"['email', 'phone']",...,5,0,5,0,7.55,Zi,5,t,119,$71.00
3021,3021,979957999730575703,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/464592319,NaN,99%,t,2,"['email', 'phone']",...,1,1,0,0,10.35,Sheila,1,t,159,$78.00
3112,3112,1008885829311227831,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/106211290,"Langford, Canada",98%,t,1,"['email', 'phone']",...,1,1,0,0,11.45,Kristopher,1,t,158,$79.00

In [154]:
datosb.to_csv("Datos Anuncios > 100 reseñas.csv", index=False)

In [155]:
# (c) 

if 'host_is_superhost' in victoriabc.columns:
    datosc = victoriabc[victoriabc['host_is_superhost'] == 't']
else:
    print("Advertencia: la columna 'host_is_superhost' no se encontró. Se omite el filtro 'super_host'.")

In [156]:
datosc.to_csv("Datos Super Host.csv", index=False)

In [157]:
# d) Rows multiples of 200

datosd = victoriabc.iloc[::200]

In [158]:
datosd.to_csv("Datos filtro filas.csv", index=False)

In [159]:
# e) Room types: "Entire home" and "Private room"
if 'property_type' in victoriabc.columns:
    datose = ['Entire home', 'Private room']

print('property_type' in victoriabc.columns)

True

In [160]:
datose.to_csv("Datos tipos de cuarto.csv", index=False)

AttributeError: 'list' object has no attribute 'to_csv'

In [ ]:
# f) Maximum 4 beds
if 'beds' in victoriabc.columns:
    datosf = victoriabc[victoriabc['beds'] <= 4]

In [ ]:
datosf.to_csv("Datos maximo 4 camas.csv", index=False)

In [ ]:
# g) Instant bookable
if 'has_availability' in victoriabc.columns:
    datosg = victoriabc[victoriabc['has_availability'] == 't']
print('has_availability' in victoriabc.columns)

True

In [ ]:
datosg.to_csv("Datos Instant .csv", index=False)

In [ ]:
# h) Odd columns
victoriabc.iloc[:, ::2]

,Unnamed: 0,scrape_id,host_url,host_acceptance_rate,host_total_listings_count,longitude,bathrooms,bedrooms,amenities,maximum_nights,...,first_review,review_scores_rating,review_scores_cleanliness,review_scores_communication,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_private_rooms,reviews_per_month,host_listings_count,number_of_reviews
0,0,2.024120e+13,https://www.airbnb.com/users/show/69729,NaN,6,-123.339770,NaN,1.0,"[""Free parking on premises"", ""Breakfast"", ""Wif...",30,...,NaN,NaN,NaN,NaN,NaN,1,1,NaN,1,0
1,1,2.024120e+13,https://www.airbnb.com/users/show/173169,99%,6,-123.370650,1.0,1.0,"[""Free parking on premises"", ""Outdoor furnitur...",90,...,04/07/13,4.29,4.42,4.57,4.23,3,0,0.50,3,70
2,2,2.024120e+13,https://www.airbnb.com/users/show/455118,97%,4,-123.499960,1.0,1.0,"[""Free parking on premises"", ""Dishes and silve...",730,...,05/05/11,4.88,4.87,4.84,4.75,2,0,0.89,2,148
3,3,2.024120e+13,https://www.airbnb.com/users/show/802981,NaN,3,-123.367900,2.5,2.0,"[""Free parking on premises"", ""Dishes and silve...",180,...,09/08/12,4.91,4.98,4.92,4.90,1,0,0.42,1,64
4,4,2.024120e+13,https://www.airbnb.com/users/show/880366,0%,3,-123.463570,1.0,2.0,"[""Free parking on premises"", ""Hair dryer"", ""Sm...",365,...,17/08/11,4.72,4.65,4.88,4.61,3,3,0.32,3,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3946,3946,2.024120e+13,https://www.airbnb.com/users/show/548256873,100%,6,-124.402109,1.0,3.0,"[""Free parking on premises"", ""Hair dryer"", ""Sm...",30,...,NaN,NaN,NaN,NaN,NaN,3,0,NaN,6,0
3947,3947,2.024120e+13,https://www.airbnb.com/users/show/668062525,NaN,1,-123.414387,1.0,1.0,"[""Free parking on premises"", ""Dishes and silve...",1125,...,NaN,NaN,NaN,NaN,NaN,1,0,NaN,1,0
3948,3948,2.024120e+13,https://www.airbnb.com/users/show/290549710,NaN,1,-123.395233,1.0,2.0,"[""TV"", ""Free parking on premises"", ""Kitchen"", ...",365,...,NaN,NaN,NaN,NaN,NaN,1,0,NaN,1,0
3949,3949,2.024120e+13,https://www.airbnb.com/users/show/112019210,91%,4,-123.545252,1.0,1.0,"[""Free parking on premises"", ""Long term stays ...",365,...,26/12/24,5.00,5.00,5.00,5.00,1,0,1.00,1,1
3950,3950,2.024120e+13,https://www.airbnb.com/users/show/32614142,98%,118,-123.369628,1.0,1.0,"[""Free parking on premises"", ""Outdoor furnitur...",365,...,NaN,NaN,NaN,NaN,NaN,53,0,NaN,55,0

In [ ]:
victoriabc.to_csv("Datos impares.csv", index=False)

***Actividad 2***

In [ ]:
# a) Acceptance rate and super host

print(victoriabc['host_acceptance_rate'].dtype)

float64

In [ ]:

victoriabc['host_acceptance_rate'] = victoriabc['host_acceptance_rate'].str.replace('%', '').astype(float)

In [165]:
victoriabc['host_is_superhost'] = victoriabc['host_is_superhost'].map({'True': True, 'False': False})

In [166]:
victoriabc['host_is_superhost'] = victoriabc['host_is_superhost'].astype(bool)

In [167]:
print(victoriabc['host_is_superhost'].dtype)

bool

In [170]:
datosa2 = victoriabc[(victoriabc['host_acceptance_rate'] > 95) & (~victoriabc['host_is_superhost'])]
datosa2

Empty DataFrame
Columns: [Unnamed: 0, id, scrape_id, last_scraped, host_url, host_location, host_acceptance_rate, host_is_superhost, host_total_listings_count, host_verifications, longitude, property_type, bathrooms, bathrooms_text, bedrooms, beds, amenities, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, availability_60, availability_90, availability_365, calendar_last_scraped, number_of_reviews_ltm, number_of_reviews_l30d, first_review, last_review, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, license, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month, host_name, host_listings_count, has_availability, number_of_reviews, price]
Index: []

[0 rows x 52 columns]

In [179]:
datosa2.to_csv("Datos Rate Superhost.csv", index=False)

In [181]:
#b) 1 baño

datosbaño = victoriabc[victoriabc['bathrooms'] != 1]
datosbaño

,Unnamed: 0,id,scrape_id,last_scraped,host_url,host_location,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_name,host_listings_count,has_availability,number_of_reviews,price
0,0,19898,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/69729,NaN,NaN,True,6,"['email', 'phone']",...,1,0,1,0,NaN,Ryan,1,NaN,0,NaN
3,3,168460,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/802981,"Victoria, Canada",NaN,True,3,"['email', 'phone', 'work_email']",...,1,1,0,0,0.42,Deborah,1,t,64,$200.00
5,5,193366,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/937766,"Victoria, Canada",100.0,True,1,"['email', 'phone']",...,1,1,0,0,1.00,Sandra,1,t,157,$135.00
10,10,226030,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/1178351,"Victoria, Canada",100.0,True,2,"['email', 'phone', 'work_email']",...,2,2,0,0,0.07,Allison,2,t,8,NaN
17,17,408315,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/2032438,NaN,100.0,True,1,"['email', 'phone']",...,1,1,0,0,0.19,A,1,t,24,$377.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3913,3913,1302997863073985323,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/658337247,NaN,NaN,True,1,['phone'],...,1,1,0,0,NaN,Buddi,1,t,0,"$2,000.00"
3918,3918,1303278477790226126,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/40653407,"Victoria, Canada",91.0,True,2,"['email', 'phone']",...,1,1,0,0,NaN,David,2,t,0,$289.00
3929,3929,1309774171835273959,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/22264832,"Victoria, Canada",100.0,True,1,"['email', 'phone', 'work_email']",...,1,1,0,0,NaN,Subhash Chandra,1,t,0,$100.00
3937,3937,1312530336729382434,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/266695325,"Victoria, Canada",83.0,True,1,"['email', 'phone']",...,1,1,0,0,1.00,Jennifer,1,t,1,$162.00
3944,3944,1314683517774131164,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/27230436,NaN,NaN,True,3,"['email', 'phone']",...,1,1,0,0,NaN,Tony,1,t,0,$170.00

In [182]:
datosa2.to_csv("Datos 1 bathroom.csv", index=False)

In [186]:
#c) Precios entre 100 y 200
print(victoriabc['price'].dtype)

object

In [187]:
victoriabc['price'] = victoriabc['price'].str.replace('$', '').str.replace(',', '').astype(float)

In [188]:
datosc2 = victoriabc[(victoriabc['price'] >= 100) & (victoriabc['price'] <= 200)]

In [189]:
datosc2 = victoriabc[(victoriabc['price'] >= 100) & (victoriabc['price'] <= 200)]
datosc2

,Unnamed: 0,id,scrape_id,last_scraped,host_url,host_location,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_name,host_listings_count,has_availability,number_of_reviews,price
2,2,83515,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/455118,"British Columbia, Canada",97.0,True,4,"['email', 'phone']",...,2,2,0,0,0.89,Celia,2,t,148,175.0
3,3,168460,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/802981,"Victoria, Canada",NaN,True,3,"['email', 'phone', 'work_email']",...,1,1,0,0,0.42,Deborah,1,t,64,200.0
4,4,185732,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/880366,"Victoria, Canada",0.0,True,3,"['email', 'phone', 'work_email']",...,3,0,3,0,0.32,Peter,3,t,52,199.0
5,5,193366,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/937766,"Victoria, Canada",100.0,True,1,"['email', 'phone']",...,1,1,0,0,1.00,Sandra,1,t,157,135.0
7,7,201441,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/880366,"Victoria, Canada",0.0,True,3,"['email', 'phone', 'work_email']",...,3,0,3,0,0.10,Peter,3,t,12,139.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3942,3942,1314652550456408670,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/454617002,"British Columbia, Canada",99.0,True,151,"['email', 'phone']",...,22,0,22,0,NaN,Evergreen Hospitality,145,t,0,131.0
3943,3943,1314652726394086067,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/454617002,"British Columbia, Canada",99.0,True,151,"['email', 'phone']",...,22,0,22,0,NaN,Evergreen Hospitality,145,t,0,131.0
3944,3944,1314683517774131164,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/27230436,NaN,NaN,True,3,"['email', 'phone']",...,1,1,0,0,NaN,Tony,1,t,0,170.0
3947,3947,1316608634341666791,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/668062525,NaN,NaN,True,1,"['email', 'phone']",...,1,1,0,0,NaN,Charlotte Jane,1,t,0,128.0
3950,3950,1318259877390189592,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/32614142,"Victoria, Canada",98.0,True,118,"['email', 'phone', 'work_email']",...,53,53,0,0,NaN,Elite Vacation Homes,55,t,0,148.0

In [191]:
datosc2.to_csv("Datos Price.csv", index=False)

In [199]:
#d) Total listings
datosd2 = victoriabc[victoriabc['host_total_listings_count'] > 5]
datosd2

,Unnamed: 0,id,scrape_id,last_scraped,host_url,host_location,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_name,host_listings_count,has_availability,number_of_reviews,price
1229,1229,40122004,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/297265233,NaN,99.0,True,10,['phone'],...,9,7,2,0,0.02,Alexander,9,t,1,55.0
1434,1434,45314164,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/34315109,"Victoria, Canada",54.0,True,45,"['email', 'phone']",...,29,0,29,0,0.07,Carol Ann,29,t,1,50.0
1622,1622,49534925,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/110365117,"Squamish, Canada",48.0,True,7,"['email', 'phone']",...,7,2,5,0,0.89,Andrew,7,t,38,175.0
1624,1624,49590174,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/110365117,"Squamish, Canada",48.0,True,7,"['email', 'phone']",...,7,2,5,0,0.49,Andrew,7,t,21,159.0
1625,1625,49590710,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/110365117,"Squamish, Canada",48.0,True,7,"['email', 'phone']",...,7,2,5,0,0.69,Andrew,7,t,29,149.0
1626,1626,49591308,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/110365117,"Squamish, Canada",48.0,True,7,"['email', 'phone']",...,7,2,5,0,1.22,Andrew,7,t,52,159.0
1636,1636,49877269,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/110365117,"Squamish, Canada",48.0,True,7,"['email', 'phone']",...,7,2,5,0,0.39,Andrew,7,t,16,175.0
2409,2409,764803845156113357,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/40738526,"Sooke, Canada",78.0,True,36,"['email', 'phone']",...,1,0,1,0,0.99,Candace,2,t,24,NaN
2765,2765,903489069957681570,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/34315109,"Victoria, Canada",54.0,True,45,"['email', 'phone']",...,29,0,29,0,0.15,Carol Ann,29,t,1,50.0
3440,3440,1152823290309144196,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/34315109,"Victoria, Canada",54.0,True,45,"['email', 'phone']",...,29,0,29,0,NaN,Carol Ann,29,t,0,NaN

In [200]:
datosd2.to_csv("Datos Total Listings.csv", index=False)

In [196]:
#e)
datose2 = victoriabc[victoriabc['property_type'].isin(['hotel room', 'Private room'])]
victoriabc

,Unnamed: 0,id,scrape_id,last_scraped,host_url,host_location,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_name,host_listings_count,has_availability,number_of_reviews,price
334,334,12925681,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/15028064,"British Columbia, Canada",100.0,True,3,"['email', 'phone']",...,1,0,1,0,2.55,Dorrie,3,t,257,NaN
1066,1066,35317460,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/203180961,NaN,60.0,True,2,['phone'],...,1,0,1,0,0.40,Elizabeth,1,t,26,289.0
1229,1229,40122004,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/297265233,NaN,99.0,True,10,['phone'],...,9,7,2,0,0.02,Alexander,9,t,1,55.0
1434,1434,45314164,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/34315109,"Victoria, Canada",54.0,True,45,"['email', 'phone']",...,29,0,29,0,0.07,Carol Ann,29,t,1,50.0
1622,1622,49534925,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/110365117,"Squamish, Canada",48.0,True,7,"['email', 'phone']",...,7,2,5,0,0.89,Andrew,7,t,38,175.0
1624,1624,49590174,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/110365117,"Squamish, Canada",48.0,True,7,"['email', 'phone']",...,7,2,5,0,0.49,Andrew,7,t,21,159.0
1625,1625,49590710,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/110365117,"Squamish, Canada",48.0,True,7,"['email', 'phone']",...,7,2,5,0,0.69,Andrew,7,t,29,149.0
1626,1626,49591308,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/110365117,"Squamish, Canada",48.0,True,7,"['email', 'phone']",...,7,2,5,0,1.22,Andrew,7,t,52,159.0
1636,1636,49877269,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/110365117,"Squamish, Canada",48.0,True,7,"['email', 'phone']",...,7,2,5,0,0.39,Andrew,7,t,16,175.0
2130,2130,646526684625362269,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/26972755,"Victoria, Canada",100.0,True,1,"['email', 'phone']",...,1,0,1,0,3.95,Sue & Jenny,1,t,121,NaN
2409,2409,764803845156113357,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/40738526,"Sooke, Canada",78.0,True,36,"['email', 'phone']",...,1,0,1,0,0.99,Candace,2,t,24,NaN
2765,2765,903489069957681570,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/34315109,"Victoria, Canada",54.0,True,45,"['email', 'phone']",...,29,0,29,0,0.15,Carol Ann,29,t,1,50.0
3440,3440,1152823290309144196,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/34315109,"Victoria, Canada",54.0,True,45,"['email', 'phone']",...,29,0,29,0,NaN,Carol Ann,29,t,0,NaN

In [197]:
datose2.to_csv("Datos 'Hotel' 'Private'.csv", index=False)

In [203]:
#f) 2 > bedrooms
datosf2 = victoriabc[victoriabc['availability_365'] > 300]
datosf2

,Unnamed: 0,id,scrape_id,last_scraped,host_url,host_location,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_verifications,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_name,host_listings_count,has_availability,number_of_reviews,price
1434,1434,45314164,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/34315109,"Victoria, Canada",54.0,True,45,"['email', 'phone']",...,29,0,29,0,0.07,Carol Ann,29,t,1,50.0
2765,2765,903489069957681570,2.024120e+13,29/12/24,https://www.airbnb.com/users/show/34315109,"Victoria, Canada",54.0,True,45,"['email', 'phone']",...,29,0,29,0,0.15,Carol Ann,29,t,1,50.0

In [204]:
datosf2.to_csv("Datos Availability.csv", index=False)